-- AlterTable
ALTER TABLE `Project` MODIFY `dealStatus` ENUM('INVOICE_ISSUED', 'ACTUAL', 'REJECT', 'PAID', 'APPROVAL', 'UNDER_APPROVAL', 'FIRST_CP_APPROVAL', 'CONTRACT_ADVANCE_PAYMENT', 'PROGRESS', 'DELIVERY_WORKS', 'SIGN_ACTS_PAYMENT', 'CLOSED') NOT NULL;
