export const defaultProjectValues = {
  dateRequest: undefined,
  nameObject: "",
  nameDeal: "",
  direction: "",
  deliveryType: undefined,
  contact: "",
  phone: "",
  email: "",
  amountCP: "",
  amountWork: "",
  amountPurchase: "",
  delta: "",
  dealStatus: "",
  comments: "",
  peojectId: "",
  plannedDateConnection: undefined,
  resource: "",
  contacts: [],
  managersIds: [],
};

export const defaultRetailValues = {
  dateRequest: undefined,
  nameDeal: "",
  nameObject: "",
  direction: "",
  deliveryType: undefined,
  contact: "",
  phone: "",
  email: "",
  amountCP: "",
  delta: "",
  dealStatus: "",
  comments: "",
  plannedDateConnection: undefined,
  retailsId: "",
  resource: "",
  contacts: [],
  managersIds: [],
};
