import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { CalendarProvider } from "../context/calendar-context";
import { EventsActionProvider } from "../context/events-action-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CalendarProvider>
          <EventsActionProvider>
            <div className="max-w-[1980px] m-auto overflow-hidden">
              {children}
            </div>
          </EventsActionProvider>
        </CalendarProvider>
      </body>
    </html>
  );
}
