name: Run Every Minute

on:
  workflow_dispatch: # Возможность ручного запуска
  schedule:
    - cron: "*/5 * * * *" # Каждую минуту

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notifications
        run: |
          curl -X GET https://report-app-ertel.vercel.app/api/telegram/check-and-notify 
